export const REGION_LIST = [
  { label: 'Kanto', value: 'kanto' },
  { label: 'Johto', value: 'johto' },
  { label: 'Hoenn', value: 'hoenn' },
  { label: 'Sinnoh', value: 'sinnoh' },
  { label: 'Unova', value: 'unova' },
  { label: 'Kalos', value: 'kalos' },
  { label: 'Alola', value: 'alola' },
  { label: 'Galar', value: 'galar' },
  { label: 'Paldea', value: 'paldea' },
];
export const TYPE_LIST = [
  'Normal',
  'Fire',
  'Water',
  'Grass',
  'Electric',
  'Ice',
  'Fighting',
  'Poison',
  'Ground',
  'Flying',
  'Psychic',
  'Bug',
  'Rock',
  'Ghost',
  'Dark',
  'Dragon',
  'Steel',
  'Fairy',
];

export const typeColors = {
  normal: '#A8A878',
  fire: '#F08030',
  water: '#6890F0',
  electric: '#F8D030',
  grass: '#78C850',
  ice: '#98D8D8',
  fighting: '#C03028',
  poison: '#A040A0',
  ground: '#E0C068',
  flying: '#A890F0',
  psychic: '#F85888',
  bug: '#A8B820',
  rock: '#B8A038',
  ghost: '#705898',
  dragon: '#7038F8',
  dark: '#705848',
  steel: '#B8B8D0',
  fairy: '#EE99AC',
};
